# This file is the the default one, it will be update each time the plugin
# reload/restart, so don't edit it. You will loose or work.
# Use the en-US.yml or fr-CA.yml or create your own based on this one ;)
notAnAmount: "This is not an amount: '%s'! Example: 2500 or 1535.25"
noGroupFound: "No group {%s} found..."
deletedGroup: "%s was been deleted. All worlds is now in the default group"
groupNotExist: "%s does not exist, you need to create it first"
worldNotExist:  "The world '%s' seems not exist. Check if world is case sensitive."
worldMoved: "The world {%s} as been moved in {%s}"
opPermission: "You need to be op to do that!"
havePermission: "You don't have the permission '%s'!"
notOnline: "%s is not online!"
notInSameWorld: "%s is not in the same world as you!"
notEnoughAmount: "Well! Not sure this amount is enough!"
notEnoughMoney: "Not enough money!"
transactionFailed: "Transaction failed sorry ask an OP to check console!"
paidTo: "You paid %s to %s!"
paidFrom: "Thanks to %s that give you %s!"
killVsDeath: "In %s - %s kills vs %s death."
yourRate: "Your ratio is %s"
haveNow: "%s have now %s in %s"
payGroupNotFound: "Group {%s} not found - case sensitive or player not visited yet!"
payPlayerNotFound: "Player {%s} not found!"
groupAdded: "Group {%s} has been added with a starting balance of %s"
groupSetAmount: "Group {%s} set is starting balance to %s"
lastUpdate: "Last Update"
somethingWrongHappen: "Sorry but something wrong happen... Try again!"