## CONFIG FOR THE MULTIWORLDMONEY
## This file is just a helper file. Nothing will be load from this file
version: '2.2.9'

## If true this will add all new world not listed in Default group
## If false this will create a new group with only this world in this group
newWorldInDefault: true

## delay in second to refresh the baltop !!! WARNING more the number is lower than 20sec
##  more the server will calculate the baltop and can be slower
baltopdelay: 20

